version: "3.3"

services:
  importer:
    volumes:
      - ../data:/var/lib/hedera-mirror-importer
      - ../application.yml:/usr/etc/hedera-mirror-importer/application.yml
      - ../local-dev-1-node.addressbook.f102.json.bin:/usr/etc/hedera-mirror-importer/local-dev-1-node.addressbook.f102.json.bin
  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    volumes:
      - ../compose-network/node0/streams:/data
    ports:
      - "9000:9000"